version: '2'

services:

  app:
    image: ${REGISTRY}go-demo
    ports:
      - 8080
    depends_on:
      - db
    networks:
      default:
        aliases:
          - go-demo-net

  db:
    image: mongo
