version: '2'

services:

  unit:
    image: golang:1.6
    volumes:
      - .:/usr/src/myapp
    command: bash -c "cd /usr/src/myapp && go get -d -v -t && go build -v -o go-demo"

  build:
    build: .
    image: ${REGISTRY}go-demo
